# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0005_auto_20191108_1719'),
        ('device', '0002_auto_20191105_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_num', models.CharField(max_length=100, unique=True, verbose_name='模具编号')),
                ('m_name', models.CharField(blank=True, max_length=100, verbose_name='模具名称')),
                ('m_count', models.CharField(blank=True, max_length=100, verbose_name='模腔数')),
                ('m_life', models.CharField(blank=True, max_length=100, verbose_name='模具寿命')),
                ('m_product', models.CharField(blank=True, max_length=100, verbose_name='生产模数')),
                ('m_status', models.CharField(choices=[('1', '生产'), ('2', '空闲'), ('3', '维修'), ('4', '保养')], max_length=100, verbose_name='模具状态')),
                ('m_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('m_device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mold_device', to='device.DeviceMd', verbose_name='关联设备')),
                ('m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mold_adds', to='rbac.UserInfo', verbose_name='维护人员')),
            ],
            options={
                'verbose_name': '模具',
                'verbose_name_plural': '模具',
            },
        ),
    ]
