# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-16 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mold',
            name='m_device',
        ),
    ]
