# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0003_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='mr_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
