# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0006_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='mr_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
    ]
