# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0002_auto_20191105_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_time', models.FloatField(blank=True, null=True, verbose_name='时间')),
                ('e_tem', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('e_place', models.FloatField(blank=True, null=True, verbose_name='位置')),
                ('e_pressure', models.FloatField(blank=True, null=True, verbose_name='压力')),
                ('t_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramerror', to='device.DeviceMd')),
            ],
        ),
        migrations.CreateModel(
            name='ParamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_open_place1', models.FloatField(default=0, verbose_name='开模一段位置')),
                ('s_open_pressure1', models.FloatField(default=0, verbose_name='开模一段压力')),
                ('s_open_speed1', models.FloatField(default=0, verbose_name='开模一段速度')),
                ('s_open_place2', models.FloatField(default=0, verbose_name='开模二段位置')),
                ('s_open_pressure2', models.FloatField(default=0, verbose_name='开模二段压力')),
                ('s_open_speed2', models.FloatField(default=0, verbose_name='开模二段速度')),
                ('s_open_place3', models.FloatField(default=0, verbose_name='开模三段位置')),
                ('s_open_pressure3', models.FloatField(default=0, verbose_name='开模三段压力')),
                ('s_open_speed3', models.FloatField(default=0, verbose_name='开模三段速度')),
                ('s_open_place4', models.FloatField(default=0, verbose_name='开模四段位置')),
                ('s_open_pressure4', models.FloatField(default=0, verbose_name='开模四段压力')),
                ('s_open_speed4', models.FloatField(default=0, verbose_name='开模四段速度')),
                ('s_open_place5', models.FloatField(default=0, verbose_name='开模五段位置')),
                ('s_open_pressure5', models.FloatField(default=0, verbose_name='开模五段压力')),
                ('s_open_speed5', models.FloatField(default=0, verbose_name='开模五段速度')),
                ('t_open_mold', models.FloatField(default=0, verbose_name='开模时间')),
                ('t_close_mold', models.FloatField(default=0, verbose_name='关模时间')),
                ('t_stock', models.FloatField(default=0, verbose_name='储料时间')),
                ('t_ejection', models.FloatField(default=0, verbose_name='射出时间')),
                ('t_back', models.FloatField(default=0, verbose_name='射退时间')),
                ('t_change', models.FloatField(default=0, verbose_name='转保压时间')),
                ('t_change_place', models.FloatField(default=0, verbose_name='转保压位置')),
                ('t_change_pressure', models.FloatField(default=0, verbose_name='转保压压力')),
                ('t_tem1', models.FloatField(default=0)),
                ('t_tem2', models.FloatField(default=0)),
                ('t_tem3', models.FloatField(default=0)),
                ('t_tem4', models.FloatField(default=0)),
                ('t_tem5', models.FloatField(default=0)),
                ('t_open_place', models.FloatField(default=0)),
                ('t_ejection1', models.FloatField(default=0, verbose_name='射出起点')),
                ('t_ejection2', models.FloatField(default=0, verbose_name='射出终点')),
                ('t_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('t_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramset', to='device.DeviceMd')),
            ],
        ),
        migrations.CreateModel(
            name='ParamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_all', models.FloatField(default=0, verbose_name='循环时间')),
                ('t_open_mold', models.FloatField(default=0)),
                ('t_close_mold', models.FloatField(default=0)),
                ('t_stock', models.FloatField(default=0, verbose_name='储料时间')),
                ('t_ejection', models.FloatField(default=0, verbose_name='射出时间')),
                ('t_back', models.FloatField(default=0, verbose_name='射退时间')),
                ('t_change', models.FloatField(default=0, verbose_name='转保压时间')),
                ('t_change_place', models.FloatField(default=0, verbose_name='转保压位置')),
                ('t_change_pressure', models.FloatField(default=0, verbose_name='转保压压力')),
                ('t_tem1', models.FloatField(default=0)),
                ('t_tem2', models.FloatField(default=0)),
                ('t_tem3', models.FloatField(default=0)),
                ('t_tem4', models.FloatField(default=0)),
                ('t_tem5', models.FloatField(default=0)),
                ('t_open_place', models.FloatField(default=0)),
                ('t_ejection1', models.FloatField(default=0, verbose_name='射出起点')),
                ('t_ejection2', models.FloatField(default=0, verbose_name='射出终点')),
                ('t_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('t_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramtime', to='device.DeviceMd')),
            ],
        ),
    ]
