# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramerror',
            name='e_remind',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='提醒人'),
        ),
    ]
