# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_paramerror_e_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramtime',
            name='t_error',
            field=models.BooleanField(default=None),
        ),
    ]
