# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_auto_20191223_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramset',
            name='s_open_place1',
            field=models.FloatField(default=0, null=True, verbose_name='开模一段位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_place2',
            field=models.FloatField(default=0, null=True, verbose_name='开模二段位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_place3',
            field=models.FloatField(default=0, null=True, verbose_name='开模三段位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_place4',
            field=models.FloatField(default=0, null=True, verbose_name='开模四段位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_place5',
            field=models.FloatField(default=0, null=True, verbose_name='开模五段位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_pressure1',
            field=models.FloatField(default=0, null=True, verbose_name='开模一段压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_pressure2',
            field=models.FloatField(default=0, null=True, verbose_name='开模二段压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_pressure3',
            field=models.FloatField(default=0, null=True, verbose_name='开模三段压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_pressure4',
            field=models.FloatField(default=0, null=True, verbose_name='开模四段压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_pressure5',
            field=models.FloatField(default=0, null=True, verbose_name='开模五段压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_speed1',
            field=models.FloatField(default=0, null=True, verbose_name='开模一段速度'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_speed2',
            field=models.FloatField(default=0, null=True, verbose_name='开模二段速度'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_speed3',
            field=models.FloatField(default=0, null=True, verbose_name='开模三段速度'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_speed4',
            field=models.FloatField(default=0, null=True, verbose_name='开模四段速度'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='s_open_speed5',
            field=models.FloatField(default=0, null=True, verbose_name='开模五段速度'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_back',
            field=models.FloatField(default=0, null=True, verbose_name='射退时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_change',
            field=models.FloatField(default=0, null=True, verbose_name='转保压时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_change_place',
            field=models.FloatField(default=0, null=True, verbose_name='转保压位置'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_change_pressure',
            field=models.FloatField(default=0, null=True, verbose_name='转保压压力'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_close_mold',
            field=models.FloatField(default=0, null=True, verbose_name='关模时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_ejection',
            field=models.FloatField(default=0, null=True, verbose_name='射出时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_ejection1',
            field=models.FloatField(default=0, null=True, verbose_name='射出起点'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_ejection2',
            field=models.FloatField(default=0, null=True, verbose_name='射出终点'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_open_mold',
            field=models.FloatField(default=0, null=True, verbose_name='开模时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_open_place',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_stock',
            field=models.FloatField(default=0, null=True, verbose_name='储料时间'),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_tem1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_tem2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_tem3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_tem4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramset',
            name='t_tem5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_all',
            field=models.FloatField(default=0, null=True, verbose_name='循环时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_back',
            field=models.FloatField(default=0, null=True, verbose_name='射退时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_change',
            field=models.FloatField(default=0, null=True, verbose_name='转保压时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_change_place',
            field=models.FloatField(default=0, null=True, verbose_name='转保压位置'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_change_pressure',
            field=models.FloatField(default=0, null=True, verbose_name='转保压压力'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_close_mold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_ejection',
            field=models.FloatField(default=0, null=True, verbose_name='射出时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_ejection1',
            field=models.FloatField(default=0, null=True, verbose_name='射出起点'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_ejection2',
            field=models.FloatField(default=0, null=True, verbose_name='射出终点'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_open_mold',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_open_place',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_stock',
            field=models.FloatField(default=0, null=True, verbose_name='储料时间'),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_tem1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_tem2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_tem3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_tem4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paramtime',
            name='t_tem5',
            field=models.FloatField(default=0, null=True),
        ),
    ]
