# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_auto_20191224_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramerror',
            name='e_error',
            field=models.BooleanField(default=True),
        ),
    ]
