# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_paramerror_e_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramset',
            name='t_all',
            field=models.FloatField(default=0, null=True, verbose_name='循环时间'),
        ),
    ]
