# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-03 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_paramset_t_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramset',
            old_name='t_all',
            new_name='s_all',
        ),
    ]
