# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-05 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemd',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_brank',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备品牌'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_num',
            field=models.CharField(max_length=100, unique=True, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_photo',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='设备图片'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_status',
            field=models.CharField(choices=[('1', '运行'), ('2', '待机'), ('3', '离线')], max_length=100, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_type',
            field=models.CharField(choices=[('1', '注塑机'), ('2', '辅机')], max_length=100, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicemd',
            name='d_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_adds', to=settings.AUTH_USER_MODEL, verbose_name='添加人员'),
        ),
    ]
