# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20191105_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_start', models.CharField(blank=True, max_length=100, verbose_name='开始时间')),
                ('dr_end', models.CharField(blank=True, max_length=100, null=True, verbose_name='结束时间')),
                ('dr_user', models.CharField(blank=True, max_length=100, verbose_name='维修人员')),
                ('dr_des', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('dr_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='device.DeviceMd')),
            ],
        ),
    ]
