# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-31 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0003_devicerepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=32, verbose_name='订单号')),
                ('o_name', models.CharField(max_length=32, verbose_name='产品名称')),
                ('o_customer', models.CharField(max_length=32, verbose_name='客户')),
                ('o_count', models.IntegerField(verbose_name='产品数量')),
                ('o_finish', models.IntegerField(default=0, verbose_name='生产数量')),
                ('o_start', models.CharField(max_length=32, verbose_name='开始时间')),
                ('o_end', models.CharField(max_length=32, verbose_name='结束时间')),
                ('o_day', models.IntegerField(verbose_name='所需天数')),
                ('o_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('o_status', models.CharField(choices=[('1', '未开始'), ('2', '暂停中'), ('3', '生产中'), ('4', '已完成'), ('5', '未分配')], default=1, max_length=32, verbose_name='订单状态')),
                ('o_des', models.CharField(max_length=32, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField(verbose_name='订单ID')),
                ('d_id', models.IntegerField(verbose_name='机台ID')),
                ('od_count', models.IntegerField(default=0, verbose_name='生产数量')),
                ('od_active', models.BooleanField(default=True)),
                ('od_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('d_k', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='od_device', to='device.DeviceMd')),
                ('o_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_order', to='produce.Order')),
            ],
        ),
    ]
