# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdevice',
            name='od_taskid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
